# Generated by Django 5.0.7 on 2024-07-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Upload Media Root')),
                ('elo_rating', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_image1', to='comparison.image')),
                ('image2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_image2', to='comparison.image')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_winner', to='comparison.image')),
            ],
        ),
    ]
