# Generated by Django 5.0.7 on 2024-07-18 12:06

import comparison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=comparison.models.custom_upload_path),
        ),
    ]
