# Generated by Django 5.0.7 on 2024-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
