# Generated by Django 5.0.7 on 2024-07-18 13:58

import comparison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_alter_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=39)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=comparison.models.CustomImageField(upload_to=comparison.models.custom_upload_path),
        ),
    ]
